export * from './home/home.page';
export * from './login/login.page';
export * from './not-found/not-found.page';
export * from './layout/layout.page';
export * from './register/register.page';
export * from './forgot-password/forgot-password.page';
export * from './activity/activity.page';
export * from './dashboard/dashboard.page';
export * from './admin-activity/admin-activity.page';